services:
  rabbitmq:
    image: rabbitmq:3-management
    container_name: rabbitmq
    ports:
      - "5672:5672"
      - "15672:15672"
    healthcheck:
      test: ["CMD", "rabbitmq-diagnostics", "check_running"]
      interval: 5s
      timeout: 5s
      retries: 10

  search-service:
    build: .
    container_name: search_trends_service
    ports:
      - "8080:8080"
    environment:
      HTTP_ADDR: ":8080"
      AMQP_URL: "amqp://guest:guest@rabbitmq:5672/"
      QUEUE_NAME: "search_logs"
    depends_on:
      rabbitmq:
        condition: service_healthy
    restart: on-failure
    healthcheck:
      test: ["CMD", "wget", "-qO-", "http://127.0.0.1:8080/health"]
      interval: 5s
      timeout: 3s
      retries: 10
      start_period: 10s
